# Generated by Django 3.2.19 on 2023-06-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Invitation id')),
                ('name', models.CharField(max_length=200, verbose_name='nama yang diundang')),
                ('alamat', models.CharField(max_length=500, null=True, verbose_name='alamat yang di undang')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('inviter',),
            },
        ),
    ]
