# Generated by Django 3.2.19 on 2023-06-10 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengantin_lk', models.CharField(max_length=200)),
                ('nama_pengantin_pr', models.CharField(max_length=200)),
                ('nama_panggilan_lk', models.CharField(max_length=200)),
                ('nama_panggilan_pr', models.CharField(max_length=200)),
                ('nama_wali_lk_ayah', models.CharField(max_length=200)),
                ('nama_wali_lk_ibu', models.CharField(max_length=200)),
                ('nama_wali_pr_ayah', models.CharField(max_length=200)),
                ('nama_wali_pr_ibu', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
