# Generated by Django 3.2.19 on 2023-06-11 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='anonim', max_length=200, verbose_name='nama tamu')),
                ('kehadiran', models.CharField(choices=[('HA', 'Hadir'), ('TH', 'Tidak Hadir'), ('BT', 'Belum Tahu'), ('IA', 'Insya Allah Hadir')], default='HA', max_length=2)),
                ('ucapan', models.TextField(verbose_name='ucapan tamu kepada user')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inviter'],
            },
        ),
    ]
